### ISSUE TITLE
When the feed is refreshed, the current play state is lost

### ISSUE THREAD

**Issue by samschooler** [PlugForMac/Plug2Issues#100]
When the main feed is refreshed by scrolling to the top, the current song stays playing, but the player loses its state and goes from this:
![screen shot 2015-12-08 at 7 12 43 pm](https://cloud.githubusercontent.com/assets/833787/11673575/b7b589fe-9ddf-11e5-8223-c674b5c572b5.png)
to this, yet keeps playing music.
![screen shot 2015-12-08 at 7 12 54 pm](https://cloud.githubusercontent.com/assets/833787/11673579/bbfaff1c-9ddf-11e5-8fb5-b66ebef230ff.png)

**Comment by alexmarchant** [comment]
Thanks @quaz3l !

**Comment by f3ndot** [comment]
Reproducible on mine as well

**Comment by alexmarchant** [comment]
thanks to @finder39 for his contribution that fixed this
