### ISSUE TITLE
Current playing track always shows on the bottom if song switches when it is above the view.

### ISSUE THREAD

**Issue by samschooler** [PlugForMac/Plug2Issues#101]
The current song view will default to the bottom when the next song is played. Even if the next song is above the current view in the feed. For example, if I am playing a song, and scroll down a page or so, the current song view shows on top as expected, however if I click next on the keyboard or in the app, or the song ends, the current song view goes to the bottom of the screen. This is especially annoying when I scroll back to where the song is in the feed, the current song view abruptly jumps to where the song is in the feed.
### Steps to reproduce:
1. Play song:
   ![Uploading Screen Shot 2015-12-08 at 7.24.24 PM.png…]()
2. Scroll below the current song:
   ![screen shot 2015-12-08 at 7 28 56 pm](https://cloud.githubusercontent.com/assets/833787/11673908/f0cf8c4c-9de1-11e5-98c9-741bf7ef9925.png)
3. Click Next, and the current song view jumps to the bottom (bug):
   ![screen shot 2015-12-08 at 7 29 32 pm](https://cloud.githubusercontent.com/assets/833787/11673928/06bb66ac-9de2-11e5-9976-bdf95273df2b.png)
4. Scroll back to where the song is in the feed, and it jumps to the songs location (bug):
   ![screen shot 2015-12-08 at 7 30 59 pm](https://cloud.githubusercontent.com/assets/833787/11673971/3b142af6-9de2-11e5-8de8-6592da3f48cc.png)

**Comment by finder39** [comment]
I fixed this up :) should be in the current or next release!
