### ISSUE TITLE
Infinite scrolls doesn't work with regular mouse scroll, only trackpad swipeing

### ISSUE THREAD

**Issue by PederBergstrom** [PlugForMac/Plug2Issues#102]
When reaching the bottom of the favorites feed, using the trackpad I get older tracks loaded (infinite scroll style). But using my mouse scroll wheel it simply stays at the bottom without loading any more tracks.

**Comment by TechnoTom74** [comment]
I experience this as well.

**Comment by alexmarchant** [comment]
Should have been fixed several months ago, let me know if you guys still have issues here
