### ISSUE TITLE
Next/Previous buttons and keyboard buttons have no effect if sticky "now playing" header is missing

### ISSUE THREAD

**Issue by f3ndot** [PlugForMac/Plug2Issues#104]
## Steps to reproduce
1. Reproduce #103 
2. Press Next/Previous on keyboard or Plug interface

Nothing occurs in this case.

**Comment by f3ndot** [comment]
Hmm. Clarification: It only happens on the rare case that during scrubbing, the "now playing" state not only loses stickiness but is also lost on the track's position in the list. That is, there's no way to know what's currently playing– And only when it gets like that do the buttons stop working

**Comment by alexmarchant** [comment]
I believe this was fixed in one of the last releases, please let me know if you still experience this
