### ISSUE TITLE
Thumbnails are lost when switching to Popular (Last Week)

### ISSUE THREAD

**Issue by f3ndot** [PlugForMac/Plug2Issues#105]
![missing-thumbs](https://cloud.githubusercontent.com/assets/740289/11689869/d87ff9d0-9e61-11e5-911d-ce8dffe78f36.gif)

(Side note: why did Plug switch to only displaying gradient trapezoids instead of the artwork from the site?)

**Comment by erlingur** [comment]
:+1:

**Comment by sammarcus** [comment]
Are the trapezoids expected behavior for this view? I'm curious about the switch as well :)

**Comment by alexmarchant** [comment]
@f3ndot @sammarcus those are 24 hour heatmaps of track popularity

**Comment by sammarcus** [comment]
@alexmarchant oh, nice! that's pretty cool. thank you!

**Comment by TechnoTom74** [comment]
Can you add the option to show the cover art again?
