### ISSUE TITLE
Weird border around Popular icon in sidebar when window is active

### ISSUE THREAD

**Issue by erlingur** [PlugForMac/Plug2Issues#107]
![screen shot 2015-12-10 at 14 08 04](https://cloud.githubusercontent.com/assets/509720/11717293/80eb5908-9f47-11e5-8930-a33c1712ee00.png)

That border goes away when Plug² loses focus.

**Comment by alexmarchant** [comment]
@erlingur I've never seen this, does this ever happen in other apps on your machine?

**Comment by samschooler** [comment]
I also see this too. No custom settings. I think it's the hover state.

**Comment by alexmarchant** [comment]
@erlingur @quaz3l Is it always there? Or does something trigger it?

**Comment by samschooler** [comment]
It only shows when the app is active. You can press tab to move it to the different sidebar icons.
![plugbug](https://cloud.githubusercontent.com/assets/833787/11722468/6e9f191a-9f2e-11e5-9e90-9864e8da8613.gif)

**Comment by erlingur** [comment]
I have the same experience as @quaz3l. Running El Capitan 10.11.2 Beta (15C48a). Haven't updated to the full release yet. Maybe it's something to do with that? What OS version are you running @quaz3l?

**Comment by samschooler** [comment]
@erlingur same thing! That's really odd

**Comment by erlingur** [comment]
Yeah! I'll update to the final version and report back.

**Comment by erlingur** [comment]
Updated to 10.11.2 final version (which apparently took only 11 minutes from the beta version, pretty good) and the border is still there. So it's not that.

**Comment by mylescc** [comment]
I've just got the beta and seen this bug too. Running El Capitan 10.11.2 too. It seems to only appear on startup and if I click anywhere with empty space (like on a song name) it disappears and won't return till I restart.

**Comment by erlingur** [comment]
@mylescc Try tabbing. When it receives focus the outline comes again.

**Comment by maziman84** [comment]
10.11.3 problem still present

**Comment by alexmarchant** [comment]
Looks like @keith figured out how to recreate this in #129. Thanks @keith.

**Comment by erlingur** [comment]
Why is this issue closed? It's still here, even in the latest version.

![screen shot 2018-07-27 at 11 09 58](https://user-images.githubusercontent.com/509720/43317750-a0a1c472-918d-11e8-8b09-b1af091f97e0.png)

**Comment by alexmarchant** [comment]
I'm not really working on this any more, except for catastrophic bugs. Open to outside contributions though if you or someone else wants to jump in.

**Comment by erlingur** [comment]
Ahh my bad! Didn't realize! Is the code hosted somewhere? I might like to add a few things if possible.

**Comment by alexmarchant** [comment]
Ya i'll invite you to the repo. Gonna move this to email.
