### ISSUE TITLE
Feature request: Fixed position playback bar to prevent moving click target

### ISSUE THREAD

**Issue by gordo** [PlugForMac/Plug2Issues#108]
In the previous version of Plug, the playback bar was fixed at the bottom of the list, so that we always knew where to point our cursor to play/pause when quickly switching back to the app.

In Plug 2, it's now a moving click target, dependent on which song is playing. This also means the play/pause button is no longer adjacent to other functionally similar controls like previous/next track buttons.

From a usability standpoint, I'm just going to point at Fitt's Law and leave it at that. :)

(Love Plug, by the way. I just want it to be the best it can be!)

![artboard](https://cloud.githubusercontent.com/assets/79325/11723910/b9a30dee-9f3e-11e5-9438-3418404ff46e.png)

**Comment by cpk1224** [comment]
I would like this very much, as well.

**Comment by schedorg** [comment]
Voting up Gordon's request + reasoning too.

**Comment by TechnoTom74** [comment]
+1

**Comment by orcinus** [comment]
+1

**Comment by alexmarchant** [comment]
@glennui suggested on the Plug Slack group (which you're all welcome to join if you'd like) that we simply add a play/pause button next to the skip forward/backwards buttons. Seems like this might fix this issue and also not be too invasive/mess with the sticky track idea.

![image](https://cloud.githubusercontent.com/assets/953244/13940726/78be28b8-efb6-11e5-9c7d-f2b1fd056bf4.png)

Let me know what you think or if you see any issues with this?

**Comment by schedorg** [comment]
That would be perfect @alexmarchant @glennui!

**Comment by moezzie** [comment]
+1 Still using Plug 1 in part because of this
