### ISSUE TITLE
Advanced dock menu with playback options

### ISSUE THREAD

**Issue by wsmd** [PlugForMac/Plug2Issues#110]
It would be nice to have playback options and tack info in the dock menu like this:

![screen shot 2015-12-10 at 3 37 31 pm](https://cloud.githubusercontent.com/assets/2100222/11727850/6a4e984c-9f54-11e5-8a12-2170ddf99b6c.png)

**Comment by alexmarchant** [comment]
Looks like #109 is the same thing so i'm gonna close this :)
