### ISSUE TITLE
Feature-request: Airplay

### ISSUE THREAD

**Issue by nlpthk** [PlugForMac/Plug2Issues#113]
Could you guys add support for Airplay please? Thanks so much for still showing love and working on Plug for us HypeMachine users!

**Comment by alexmarchant** [comment]
@nlpthk hey, i'd love this feature personally. Any chance you're a developer and interested in contributing here?

**Comment by nlpthk** [comment]
@alexmarchant unfortunately I'm not, I'm sorry! Really wish I was though, I've been meaning to start learning actually haha

**Comment by alexmarchant** [comment]
@nlpthk no worries! Thanks for the feedback :+1:

**Comment by finder39** [comment]
I don't think its worth building this into Plug2. Sending a Mac's audio to an Airplay device is build into OS X (ahem macOS 😉); you can also use plenty of third party apps to send the audio from a single app to an Airplay device (https://rogueamoeba.com/airfoil/mac/). I vote to close this out.

**Comment by nlpthk** [comment]
@finder39 I agree haha!! Sorry this request was relevant pre-macOS. Sierra does make it easier to airplay now so I agree to not keep this feature a priority request

**Comment by finder39** [comment]
np :) I'll close it out

**Comment by alexmarchant** [comment]
I actually would love to have this feature. It would be great to be able to send music to an airplay device while keeping system sounds on the mac ¯_(ツ)_/¯

**Comment by alexmarchant** [comment]
Actually @teendev even started messing around with this feature a while ago so i'm gonna open it back up.

**Comment by nlpthk** [comment]
@alexmarchant Woohoo! Can't wait haha! Definitely awesome seeing so much activity on here
