### ISSUE TITLE
Track skipping

### ISSUE THREAD

**Issue by skllcrn** [PlugForMac/Plug2Issues#115]
This is a bug I’ve seen in the official Hype Machine Android and iOS apps, which leads me to think that’s it’s an issue on their end, probably in the API. So it seems that when the track source is removed or otherwise unreachable, that can cause the apps to skip tracks, often 10-20 tracks ahead, or come to a complete stop. In the Android Beta this could also make the app get stuck in seemingly infinite skipping. I haven’t had this issue happen in Plug 2 until today, during playing from the top in the popular tab.

**Comment by alexmarchant** [comment]
Hmm haven't run into this i don't think @skllcrn. Do you get an error message? Are the tracks disabled:

![image](https://cloud.githubusercontent.com/assets/953244/12343522/79307aaa-bb02-11e5-9d6c-c8c8d3129aae.png)

Any other info you can give me? Is it predictable at all, like does it always happen for specific tracks?

**Comment by skllcrn** [comment]
Shared a screen recording in Slack.
