### ISSUE TITLE
Crashes upon opening

### ISSUE THREAD

**Issue by jrose13** [PlugForMac/Plug2Issues#119]
Player crashed once and now every time I try to re-open it crashes instantly and then set through an endless cycle of re-open & crashing

**Comment by alexmarchant** [comment]
Can you send me the crash logs @jrose13

**Comment by jrose13** [comment]
How do I pull the crash logs?

I used appzapper to uninstall and delete a number of files and then
reinstall so I may not have the accurate ones any more.

On Thu, Jan 14, 2016 at 9:02 PM, Alex Marchant notifications@github.com
wrote:

> Can you send me the crash logs @jrose13 https://github.com/jrose13
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PlugForMac/Plug2Issues/issues/119#issuecomment-171845750
> .

## 

---

Jesse B. Rose
978.210.1446
JesseRose.com

**Comment by alexmarchant** [comment]
@jrose13 next time it crashes there should be a "Report" button, click that and you should get a big text box with the crash log inside. Can just copy past it here.
