### ISSUE TITLE
Feature request: Chromecast

### ISSUE THREAD

**Issue by willwhitney** [PlugForMac/Plug2Issues#120]
I love Plug. It's the best way that exists to listen to Hype Machine. But I use Chromecasts (the Audio variety) everywhere in my house to listen to music, and currently that means I have to use the Chromecast Chrome extension and the Hype Machine website.

I would be beyond thrilled to get Chromecast support in Plug.

Keep up the good work!

**Comment by alexmarchant** [comment]
@willwhitney I don't use a chromecast so I'm unlikely to implement this, but happy to let you or someone else jump in and contribute here
