### ISSUE TITLE
Menu icon + functions

### ISSUE THREAD

**Issue by azabmoh** [PlugForMac/Plug2Issues#121]
Used to love the ability in the Version1's menu drawer to "like" "previous, play/pause, next" with song info. Where has that gone and can we have that feature back?

**Comment by glennui** [comment]
Pretty much a case of focussing dev on the main view itself. Reintroducing it may require a bit of a rewrite (old Plug wasn't Swift).

However I'm looking into some ways that we could improve on it, as it was pretty barebones. Something users could trigger by keyboard shortcuts so it isn't interrupting their workflow, as well as clicking a menu icon to trigger it.
