### ISSUE TITLE
Make source available to the community?

### ISSUE THREAD

**Issue by moezzie** [PlugForMac/Plug2Issues#122]
Hey there devs!

Great job on Plug so far!
Using it most hours of the day.

How come the source is not available to the community here on Github?
From the link on the website it seems to me like you would welcome more developers to the project.
I would think, having to compose an email asking permission to help out and get access to the source is just another hurdle.
What do you think?

Would love to be able to contribute through a pull request from time to time.

Cheers!

**Comment by alexmarchant** [comment]
It was a request from the Hype Machine team that we don't directly open source it. Though it might be worth revisiting this issue. I agree that the less barriers the better.

**Comment by moezzie** [comment]
Thanks for your reply Alex.

Just a quick thought without knowing anything about the code base:
Maybe it would be possible to make certain parts of the application available.
I'm guessing Hypem's concern is mostly regarding the code/libraries that connect to and "burden" their servers.

So making the source of the GUI available might be less of an issue.

**Comment by sindresorhus** [comment]
Plug is now open source: https://github.com/PlugForMac/Plug2Issues/issues/174
