### ISSUE TITLE
Scroll-to-load doesn't work with non-Apple input devices

### ISSUE THREAD

**Issue by awfy** [PlugForMac/Plug2Issues#125]
Using a Logitech mouse instead of a Magic Mouse or my MacBook's Trackpad prevents me from loading more tracks on a list view. The only workaround I can find is to drag the scrollbar to the bottom which seems to trigger the loading of more tracks.

**Comment by alexmarchant** [comment]
Just pushed 2.0.9 which should fix this for you. I don't actually have any non-apple mice to test this on so please let me know if you continue to have issues.

**Comment by awfy** [comment]
@alexmarchant just tested this and it works now! 👍
