### ISSUE TITLE
Tab selection is highlighted all the time

### ISSUE THREAD

**Issue by keith** [PlugForMac/Plug2Issues#129]
If you enabled the "All controls" option in the keyboard tab selection preferences:

![screen shot 2016-04-27 at 10 09 18](https://cloud.githubusercontent.com/assets/283886/14861007/297a32da-0c60-11e6-9c2f-6a568a99ac48.png)

The currently selected tab item has a highlight around it 100% of the time:

![screen shot 2016-04-27 at 10 08 44](https://cloud.githubusercontent.com/assets/283886/14861014/34a7ffb6-0c60-11e6-808d-4987c0468794.png)

**Comment by alexmarchant** [comment]
Closing, will continue to keep track of this issue in #107
