### ISSUE TITLE
Opening the app throws an HTTP 401

### ISSUE THREAD

**Issue by robinebers** [PlugForMac/Plug2Issues#130]
Is it just me? Anything I can do? Using the latest version (2.0.9).

// Nevermind, apparently I got logged out. Would be great if the app would say so :)

Thanks

**Comment by alexmarchant** [comment]
Hmm, ok, let me know if this happens again. The app should detect if you've been logged out, maybe there is a bug there. I'll reopen this if i hear from anyone else.
