### ISSUE TITLE
Applescript Support

### ISSUE THREAD

**Issue by nano9g** [PlugForMac/Plug2Issues#131]
Please add support for controlling (at a minimum) play/pause, next/previous, and volume via AppleScript like iTunes, Spotify, and other media players have. Thank you!

**Comment by alexmarchant** [comment]
Any idea what it takes to support AppleScript? I'm not familiar.

**Comment by nano9g** [comment]
All I really know is that you add a dictionary that maps AppleScript commands to code in the app, but I've never done it - I've only used AppleScript from the scripting side. Looks like there's some decent info ([1](http://stackoverflow.com/a/10773994), [2](https://www.objc.io/issues/14-mac/scripting-data/)) out there though?
