### ISSUE TITLE
Add support for Time Machine

### ISSUE THREAD

**Issue by Testfliege** [PlugForMac/Plug2Issues#132]
Unless I'm too stupid to find it, I can only go to the most popular posts of last week, no further. Would be cool if that feature could be added.

**Comment by alexmarchant** [comment]
Previously this was not available via their API. I've heard that The Hype Machine iPhone app just added time machine features, so maybe they added it to the API.

**Comment by alexmarchant** [comment]
Checked the API and this feature is not there, so i'm gonna close this out.

**Comment by Testfliege** [comment]
Thanks for checking up on it, Alex. Hopefully they will open it at some point.

Cheers!

**Comment by alexmarchant** [comment]
Ya sorry about this :( Would be a good feature agree
