### ISSUE TITLE
Add support for playing the weekly Stack

### ISSUE THREAD

**Issue by jesse-c** [PlugForMac/Plug2Issues#134]
Possibly as a sidebar icon, and then the top drop menu could be the week (e.g. latest, ..)?

http://blog.hypem.com/2014/06/hype-machine-stack/

**Comment by alexmarchant** [comment]
The api docs are found here: api.hypem.com/api-docs/. I don't believe that Stack is part of that API, so I don't think this will be possible :(

**Comment by alexmarchant** [comment]
Just checked the API and didnt see this there, so i'm gonna close this out.

**Comment by jesse-c** [comment]
@ale True :( Is there a process for requesting API things from hypem, or do we just let it be till it is made available?

**Comment by alexmarchant** [comment]
You should hit up Anthony and see what he says
