### ISSUE TITLE
Play history not updating on Hype Machine

### ISSUE THREAD

**Issue by bt11** [PlugForMac/Plug2Issues#138]
My play history from Plug stopped updating Hype Machine on June 14.  (As as result not scrobbling anything to Last.fm). 

This page is on Hypem web page, under Me> History > Listening History tab.

Example of what use to show up on each play:
PLAYED ON JUN 14TH USING PLUG FOR MAC

I tried playing directly from the website, and the song was added to my play history immediately.
Tried to log out, and log back into Plug.  No play history added.
Deleted Plug in applications, downloaded the dmg again and reinstalled to applications. No play history added.

**Comment by gordo** [comment]
This seems related to this bug: https://github.com/PlugForMac/Plug2Issues/issues/140

My play history stopped updating around the same time as bt11, after June 13.
