### ISSUE TITLE
Add support for Scrobbling plays to last.fm

### ISSUE THREAD

**Issue by drzax** [PlugForMac/Plug2Issues#139]

**Comment by alexmarchant** [comment]
This is actually already a feature of Hype Machine, so we get it too, just need to set it up on hypem.com in the settings.

**Comment by drzax** [comment]
I thought that might be the case, but it doesn't appear to be working (which is why I opened a ticket). 

Plays on hypem.com Scrobble just fine, but nothing I play through Plug ends up on my last.fm account.

**Comment by alexmarchant** [comment]
Ahhh got it, mind changing the title to reflect that it’s a bug?

**Comment by drzax** [comment]
No probs I'll submit a new ticket (I didn't know it was a bug until you said it should be working).

**Comment by alexmarchant** [comment]
Thank you!
