### ISSUE TITLE
Scrobbling not working from Plug

### ISSUE THREAD

**Issue by drzax** [PlugForMac/Plug2Issues#140]
Tracks played through Plug don't make it to last.fm even though tracks played on hypem.com do.

**Comment by gordo** [comment]
I just noticed this too. The last instance of Plug for Mac as the client was on June 13, 2016 in the "Listening History" section of Hype Machine (http://hypem.com/username/history), even though I listen through Plug for Mac almost daily. After that date, only official Hype Machine clients like the iPhone app are appearing in the listening history.

**Comment by alexmarchant** [comment]
Ah that helps, probably a user agent bug on our end, or maybe a hype machine api bug. Thanks @gordo

**Comment by pugson** [comment]
@alexmarchant Any updates for this issue? Using the app with last.fm scrobbling is a must for me.

**Comment by Hollowell** [comment]
Was this issue solved? I am getting this issue again now.

**Comment by alexmarchant** [comment]
@Hollowell kind of in maintenance mode here, ill probably only update if a release of macOS breaks it, open to code contributions though.

**Comment by duemir** [comment]
> open to code contributions though.

But how? The App is close sourced, as far as I can see.

**Comment by alexmarchant** [comment]
I can invite you if you'd like to contribute @duemir

**Comment by duemir** [comment]
Ah. By invite like mentioned in the README. 
I am afraid I don't have much spare time myself and don't have experience developing macOS apps.
Hence, can't commit to doing it at the moment, so no point of inviting.

**Comment by 6** [comment]
not sure about for others, but scrobbling is working for me again in the latest `Version 2.0.19 (2067)` of plug.

It doesn't work with the "Scrobbling now" `track.updateNowPlaying` status (probably an issue/limitation on the hypem side), but it does record the scrobble at the end of the song.
