### ISSUE TITLE
When no track is playing, scrolling causes instant crash

### ISSUE THREAD

**Issue by bignell** [PlugForMac/Plug2Issues#148]
Build 2064 on MacOS 10.12.2.

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]
```

On startup, tabs (Popular, Favorites, etc) will render (and are navigable), but any attempt to scroll terminates Plug, unless you've already started playing a track. Happens on any tab with the track-list view (e.g. Popular, Favorites, Recent, but not Blogs or Genres).

**Comment by alphahw** [comment]
Also getting this on 10.11.6 (using the same Plug build).

**Comment by alexmarchant** [comment]
OK, i'm seeing this too and can reproduce, will jump on this soon! Thanks

**Comment by alexmarchant** [comment]
This should have been fixed in the last update a while ago. Let me know if you still have problems.
