### ISSUE TITLE
Audio output resets on new track

### ISSUE THREAD

**Issue by zackhsi** [PlugForMac/Plug2Issues#151]
When I am airplaying Plug to speakers over wifi, it works great for the first song. After the song ends and then next song plays, the audio output comes out of my mac, not the airplay speakers.

**Comment by alexmarchant** [comment]
How are you streaming via AirPlay?

**Comment by zackhsi** [comment]
I click the sound icon in my menu bar and select an airplay output device.

**Comment by alexmarchant** [comment]
Huh ok, i haven't done this in a while, but it used to work. I'll check it out when i get home.
