### ISSUE TITLE
All operations fail with `HypeMachineAPI.ApiError Error 0`

### ISSUE THREAD

**Issue by mnkhouri** [PlugForMac/Plug2Issues#152]
As of early to mid September, Plug is no longer able to load any data from Hype Machine (playlists / feeds / favorites / blogs):

![image](https://user-images.githubusercontent.com/6535396/30870952-40184884-a2b3-11e7-8df4-86fcbc2e2cc2.png)

**Comment by alexmarchant** [comment]
Hmm, can you try 2 things:

1. Log out and log back in
2. Go to soundcloud.com and see if you can play music from there (some VPNs and networks can block or be blocked by SoundCloud)

**Comment by alexmarchant** [comment]
That is a bad error message tho :/

**Comment by mnkhouri** [comment]
Hi Alex,

Logging out and back in fixed it! 

Your diagnosis was correct, this was definitely caused by changing my Hype Machine password, but I didn't make the connection between "I changed my password a few days ago" and "Plug isn't working" :-P

Thanks for the assistance -- and thanks for the great software :)
