### ISSUE TITLE
API errors

### ISSUE THREAD

**Issue by zackhsi** [PlugForMac/Plug2Issues#153]
All of the functions fail with the same error.

<img width="468" alt="screen shot 2017-10-16 at 11 24 29 am" src="https://user-images.githubusercontent.com/806101/31628150-a8175df6-b264-11e7-831c-377cb68853ce.png">

**Comment by alexmarchant** [comment]
Hey, can you try and sign out and and sign back in. And make sure the hypem.com site is working for you from your location?

**Comment by keith** [comment]
I'm seeing this as well, but I can access hypem.com

**Comment by alexmarchant** [comment]
What specifically triggers this? I can't seem to recreate on my machine

**Comment by gordo** [comment]
I saw this same error a little over an hour ago too, but it worked again when I closed and reopened the Mac app just now.

**Comment by keith** [comment]
Looks like it's working again, may have been a blip in their API
