### ISSUE TITLE
Crashes in 2.0.17 (2065)

### ISSUE THREAD

**Issue by karstenBriksoft** [PlugForMac/Plug2Issues#154]
I keep getting a crash when i either click on the (i) button of a track or in case that doesn't crash the app, at least clicking on the link to the blog-post will then crash the app. Please find attached a crash log.

[Plug_2017-10-20-085221_Karstens-MacBook-Pro-2.crash.zip](https://github.com/PlugForMac/Plug2Issues/files/1400995/Plug_2017-10-20-085221_Karstens-MacBook-Pro-2.crash.zip)

**Comment by 01ivr3** [comment]
Same

**Comment by alexmarchant** [comment]
Sorry, basically in maintenance mode here. Open to contributions though.

**Comment by karstenBriksoft** [comment]
Can you make the source available if it's open to contribution?

**Comment by alexmarchant** [comment]
We're semi-open sourced for some reasons I can get into later. If you're interested in jumping in, lmk!

**Comment by karstenBriksoft** [comment]
I use Plug quite a lot so being able to fix crashes wouldn't be a bad thing.
