### ISSUE TITLE
Can Plug cache songs from the favourite list?

### ISSUE THREAD

**Issue by johnking7** [PlugForMac/Plug2Issues#155]
Hi,

Apologies, this may have been asked before. I did search, but maybe not perfectly.

Is it possible for Plug to cache the list of favourites? I notice when my wifi goes down (regularly when I'm travelling) - it can't play the favourites without the internet.

Or would this be against some TOS?

Thanks!

**Comment by alexmarchant** [comment]
Sorry, can't do this :( mostly just TOS stuff with SoundCloud (where most songs come from). Even the Hype Machine app for iOS dropped caching, and I could be wrong, but i believe the SoundCloud TOS stuff was the reason.

**Comment by johnking7** [comment]
Hey Alex! Thanks for letting me know. Sad to hear, but makes sense.
