### ISSUE TITLE
Touch Bar support

### ISSUE THREAD

**Issue by sughodke** [PlugForMac/Plug2Issues#156]
Could we get Touch Bar support!  Pretty please!

For inspiration, here is a mock design for Soundcloud.
![SoundCloud](https://cdn-images-1.medium.com/max/1600/1*hoQNNWXQpF37T9U5bVhxHA.jpeg)

Spotify app is currently shipping with,
![Spotify](https://i.imgur.com/f7W9f54.png)

I'd be happy to help out.

**Comment by alexmarchant** [comment]
We have had built in support for the TouchBar for a while now. We don't have any custom buttons or controls, but we do use `MPRemoteCommandCenter`, which is the setup from the Spotify screenshot in your comment. By default the controls are hidden behind the little now playing button in the control strip. If its not showing up for you, lmk.
