### ISSUE TITLE
Persistent "Network Error" on login

### ISSUE THREAD

**Issue by jordaaash** [PlugForMac/Plug2Issues#157]
System is latest Macbook Pro 2018 running High Sierra 10.13.6.

I verified internet connectivity and correctness of credentials on hypem.com.

I used AppCleaner to do a full removal followed by a reinstall from the latest dmg; no effect.

I was unable to locate any logs in `~/Library/Application Support` or Console.app, but I'm happy to provide them if there are any.

<img width="397" alt="screen shot 2018-07-21 at 3 06 16 pm" src="https://user-images.githubusercontent.com/1173161/43039670-e6b5d416-8cf7-11e8-8cbb-6dfe64130b93.png">
<img width="384" alt="screen shot 2018-07-21 at 3 06 29 pm" src="https://user-images.githubusercontent.com/1173161/43039671-e6caf42c-8cf7-11e8-966a-e8dac409fefc.png">

**Comment by Seylox** [comment]
Same for me, also on High Sierra.

**Comment by alexmarchant** [comment]
Thanks @Seylox, this is a known issue, something with the login api, we're in contact with hype machine about it.

**Comment by alexmarchant** [comment]
OK this should be fixed, let me know if you continue to see issues.

**Comment by jordaaash** [comment]
Fixed for me. Thank you!
