### ISSUE TITLE
Dark Mode on Mac OSX Mojave makes Plug unusable visually

### ISSUE THREAD

**Issue by samschooler** [PlugForMac/Plug2Issues#158]
I know this is a Beta, I just wanted to get it on your radar.
<img width="380" alt="screen shot 2018-07-27 at 14 37 01" src="https://user-images.githubusercontent.com/833787/43347563-b7017be6-91aa-11e8-9729-dfedb04f7aed.png">

**Comment by alexmarchant** [comment]
Wow, that's pretty epically bad. Wonder if there is a way to just disable
dark mode?

**Comment by samschooler** [comment]
Dark Mode is optional in the OS, but its applied globally if selected unfortunately. There may be a terminal command to toggle it per app but I have yet to find it.

**Comment by samschooler** [comment]
I would also be very down to help fix this, and work on Plug. I use it pretty much everyday.

**Comment by alexmarchant** [comment]
I'll email you.

**Comment by alexmarchant** [comment]
Pretty sure this is fixed.
