### ISSUE TITLE
Crash on startup with macOS 10.14

### ISSUE THREAD

**Issue by skllcrn** [PlugForMac/Plug2Issues#160]
Plug crashes on startup if you do not grant it access to accessibility features. Would be great to have a better flow for granting access, with an explanation of why it's necessary. 

Hope you're all doing well! ❤️

**Comment by alexmarchant** [comment]
This has been fixed, just gotta update :)

**Comment by skllcrn** [comment]
Nice! The feature request was referring to an [implementation like Dropbox](https://www.dropbox.com/help/desktop-web/mac-permissions#accessibility): 

![mac-permissions-access](https://user-images.githubusercontent.com/8440026/46287627-6f178480-c583-11e8-97c7-14d6589d61da.png)

Since Plug runs fine without access to Accessibility features, and doesn't seem to prompt for them, it shouldn't be necessary.

**Comment by alexmarchant** [comment]
Ya I hear you, we used to use the media keys to control playback. But our
library that did that do both:

- asked for accessibility permissions
- crashed

So we removed It. So now plug shouldn’t crash or ask for those permissions.
