### ISSUE TITLE
Media keys on early 2015 Macbook Pro stopped controlling Plug

### ISSUE THREAD

**Issue by skray** [PlugForMac/Plug2Issues#161]
I've come to really like that plug works with the MBP media keys (previous, next, play/pause), and (I believe) with the latest 2.0.19 release these no longer seem to work, but fall back to the default action of opening iTunes.

I've restarted my computer but still cannot seem to get Plug to work with my media keys. Any suggestions are welcome.

My system:
![image](https://user-images.githubusercontent.com/3921751/46366573-638e9100-c649-11e8-9a3a-6aff9e21f01c.png)

My plug version:
![image](https://user-images.githubusercontent.com/3921751/46366601-7d2fd880-c649-11e8-9622-079b316b436f.png)

**Comment by alexmarchant** [comment]
Ya, unfortunately, Apple never had a public API to intercept media key taps, so we used a library developed at Spotify, that was kinda hacky. It broke on Mojave and caused crashing so we had to remove it :(

Welcome to download the old release with media key support if you don't use Mojave: https://www.plugformac.com/updates/plug2/Plug-2066.dmg.

Ideally, we'd find another way to support media keys, but I don't have the time. Definitely open to contributions.

**Comment by alexmarchant** [comment]
Actually will leave open for visibility for a while.

**Comment by skray** [comment]
@alexmarchant thanks for the quick response, and for the link to the old version!

**Comment by askhogan** [comment]
@alexmarchant I am open to helping here. There is a library called [High Sierra Media Key Enable](https://github.com/milgra/highsierramediakeyenabler). It allows extensions, and sends media key input to apps like [Spotify ](https://github.com/milgra/highsierramediakeyenabler/blob/master/HighSierraMediaKeyEnabler/Spotify.h)

You mentioned above you are open to contributions. Where is the PlugForMac repo? I see the [API](https://github.com/PlugForMac/HypeMachineAPI) on your GitHub Organizations page. But I do not see the Xcode project for PlugForMac.

**Comment by askhogan** [comment]
@alexmarchant Great app BTW. Most of the web media players are so hacky. Your's is super clean and enjoyable. Love the UI and layout.

**Comment by alexmarchant** [comment]
@askhogan ya if you can figure that out we'd be pumped. It looks like that media key enabler project is a separate app. What were you thoughts on implementation there? Also i just invited you to the github repo for the code.

**Comment by askhogan** [comment]
Thanks! It is a separate app - have been running it here. Its really
lightweight and allows to fine tune where the events go. What do you think
about?

1. Phase 1 - Get the setup working as two applications. MVP. Here I could
write a lightweight implementation file to the existing app. If it works,
then we could update the README file and indicate the Advanced setup -
where two apps allow someone to enable the media buttons.
2. Phase 2 - Once the Phase 1 is successfully working, (and soak tested -
want to make sure its not glitchy) - then dig into how they are
instrumenting the connection. At that point, we could write a plugin or
extend the Plug code base - so its just one installer.

**Comment by alexmarchant** [comment]
I don't think adding a separate extension app makes sense for us. We've considered it before for this same reason, but I don't want the complexity and confusion that would come with having users install two apps. If we can extract that code and make it work inside of Plug itself, running as the same process, that would be ideal.

Just for some context. We used to use this library https://github.com/nevyn/SPMediaKeyTap. That guy works (used to work) at spotify and it was the same library that they used in their app. It's totally possible that some code in that repo simply needs to be updated to support mojave apis. Could be a 1 line update... but not sure.

**Comment by askhogan** [comment]
Thanks you for context and for direction. Completely understand your POV. I will skip Phase 1 and move on to the "Phase 2" plan. I read through the implementation of SPMediaKeyTap and
High Sierra Media Key Enabler (HSMKE). It's clear SPMediaKeyTap is using a similar pattern as HSMKE to receive a stream of keyboard events. However, the workflow logic on received event in SPMediaKeyTap is missing some of the unique event types that HSMKE has. Looks like the issue could be one of updating some switch logic (but do not want to underestimate - and curious to hear more about the glitchy behavior - below).

I just put a GSD block of time on my calendar for Saturday for this. I will
update this ticket by 10/28 to let you know how it goes. Between now and
then, I will keep jamming out to your awesome app Plug that in < 48 hours
has already made my life better. Great work!

*Questions:*
1. What bugs or glitches did you experience with SPMediaKeyTap (I want to be on the lookout this weekend for potential reasons) and on what MacOS version did these issues occur? Are there any closed Issue Tickets with clear context?
2. Did you experience these bugs only on Mojave? (in reference to your comment above that "t broke on Mojave and caused crashing" - as a user, did you experience (or have any users experience) any bugs or glitches on any MacOS versions prior to Mojave? If so, [goto question 1]

**Comment by etekweb** [comment]
I have noticed the same effect, but my skip keys are actually working. Just the (all-important) play/pause button doesn't work.

It would be nice to offer support for the third-party method, so we can download it ourselves optionally if we want media keys.

Thanks!

**Comment by capripot** [comment]
I would be happy to contribute @alexmarchant !

**Comment by bignell** [comment]
Maybe this is a dumb question, but does Plug use the (relatively new, 10.13+) MediaPlayer framework?

It looks like that's how [IINA](https://iina.io) (another media player) solved their media key issues. https://github.com/iina/iina/pull/1063

This appears to be the relevant bit: [Remote Command Center Events](https://developer.apple.com/documentation/mediaplayer/remote_command_center_events). I'm exceedingly new to macOS development, but I'd be happy to take a look and give it a stab.

**Comment by eXeDK** [comment]
Would be great to see this fixed

**Comment by kakugawa** [comment]
media keys is the main gripe I have w/ the hypem website. if you guys open source the client, i'll patch it myself.

**Comment by sindresorhus** [comment]
Plug is now open source and available on the App Store. Media keys work for me in the latest version on the App Store.

https://github.com/wulkano/Plug
