### ISSUE TITLE
Play/Pause Button in Now Playing...

### ISSUE THREAD

**Issue by marlonjames71** [PlugForMac/Plug2Issues#168]
Play/Pause button in Now Playing section of Today/Notifications sidebar doesn't work or do anything.

Dragging the scrubber works.
The previous and next track button work s well.
Just the play/pause button is the only button that seems to not be working in the Now Playing section.

MacOS: 10.14.4
Plug: 2.0.19
2018 MacBook Pro w/Touch Bar

**Comment by sindresorhus** [comment]
Fixed by https://github.com/wulkano/Plug/commit/9abcab636276a7a7c5eebf92b496875f2c8eab71

**Comment by sindresorhus** [comment]
Plug is now in the App Store: https://apps.apple.com/app/id1514182074

**Comment by marlonjames71** [comment]
Awesome sauce! Thank you!
