### ISSUE TITLE
Hype Machine API issues

### ISSUE THREAD

**Issue by sammarcus** [PlugForMac/Plug2Issues#169]
On 2.0.19 (2067), getting a standard connectivity error: 

![image](https://user-images.githubusercontent.com/8689264/57313054-c4d58180-70bc-11e9-9bb0-6d12801376d9.png)

Was there a recent change to their API?

**Comment by alexmarchant** [comment]
Is this still happening? Unfortunately the error is vague and usually means you need to log out and log back in, or check if you are behind a VPN.

**Comment by napcae** [comment]
Relogging helped me resolve this issue.
