### ISSUE TITLE
Refresh Styling

### ISSUE THREAD

**Issue by glennui** [PlugForMac/Plug2Issues#39]
For the refresh can we make it centered based on the user defined width of the application? 

To ensure the strings are roughly the same width it'd be good if:
On pull: "Last updated [time]"
On ready: "Release to Refresh"
When refreshing: "Updating Playlist"

**Comment by alexmarchant** [comment]
Updated this, the text is close in length but off enough that you have to refocus to see what the new status is. Once I push it tell me what you think, if it's enough of a shift we could just go left aligned: https://dl.dropboxusercontent.com/s/rzg2kc9lgfxhmoi/2015-07-16%20at%2011.17%20PM.png

**Comment by alexmarchant** [comment]
Just pushed the update. I've seen several iOS apps center the refresh message since building this, so i'm gonna close this unless you think it should be different.
