### ISSUE TITLE
Refresh Crash Bug

### ISSUE THREAD

**Issue by glennui** [PlugForMac/Plug2Issues#58]
http://img.glenn.me/cDZe Crashlog

If I scroll the playlist up and down a few times and then go into the Refresh area I'm find it crashes. I thought it was a sticky header issue at first, but it happens even when there's no track playing.

**Comment by alexmarchant** [comment]
Just pushed 2.0.38 which should fix this. Let me know if you still have problems.

**Comment by glennui** [comment]
Working perfectly!

**Comment by alexmarchant** [comment]
ε-(´・｀) ﾌ
