### ISSUE TITLE
Crash on Load More Favourites

### ISSUE THREAD

**Issue by glennui** [PlugForMac/Plug2Issues#65]
Scroll down and bam, crash.

**Comment by alexmarchant** [comment]
Oh man, just looked at the crash reporter. Least helpful crash log of all time, literally no idea what's going on here. Does it happen every time?

**Comment by glennui** [comment]
It's because 'hide tracks that are unavailable' is on. It works fine without that enabled.

**Comment by alexmarchant** [comment]
Ahh tracked it down, nice detective work!
