### ISSUE TITLE
Playlist stops once it cant play a track

### ISSUE THREAD

**Issue by iammart** [PlugForMac/Plug2Issues#67]
Plug stops playing once it encounters a song in a playlist in can't play rather than continuing onto the next playable track.

**Comment by alexmarchant** [comment]
#49 should fix this. It doesn't seem to happen to me super often so am currently looking to squash this one in the version right after the release version.

**Comment by iammart** [comment]
This will be super awesome. It happens with me when playing favourites which im guessing are quite old.

**Comment by alexmarchant** [comment]
This should be fixed in latest Alpha
