### ISSUE TITLE
10.11.2 beta crashes

### ISSUE THREAD

**Issue by alexmarchant** [PlugForMac/Plug2Issues#87]
https://fabric.io/plug/mac/apps/com.plug.plug2/issues/5662176ff5d3a7f76b18c2f0

**Comment by grosen** [comment]
Ditto

**Comment by dakotayounger** [comment]
Same

**Comment by alexmarchant** [comment]
Looks like an OS X bug, have been looking into a workaround for you all :|

**Comment by robertbenjamin** [comment]
Same, would love a fix for this!

**Comment by alexmarchant** [comment]
Ok got it fixed. You'll need to download a new copy here http://www.plugformac.com/.

**Comment by robertbenjamin** [comment]
Awesome that was super fast!
