### ISSUE TITLE
Restore Play/Pause button

### ISSUE THREAD

**Issue by mat-u** [PlugForMac/Plug2Issues#90]
Proposal : Play/Pause button at the bottom was very handy, as in Plug v1. Why not re-add it between the Prev/Next button ?

**Comment by alexmarchant** [comment]
@mat-u Hey thanks for the feedback! I get what you're saying. We've deliberately kept the play/pause button stickied to the track and out of the bottom area, and I think we're going to stick to that. If we here this request more from people as they start to use the app we can come back to it in the future. For now I'm going to archive it though.
