### ISSUE TITLE
Blog list following section looks like it includes all blogs

### ISSUE THREAD

**Issue by alexmarchant** [PlugForMac/Plug2Issues#92]

**Comment by jmduke** [comment]
Also an issue with the 'Featured' section.  This may be an issue with the API deserialization; a couple debug statements made it look like every single blog was `following` and `featured`, but looking at the raw JSON returned by `hypem` looks normal (only the actual blogs I'm following have the `ts_loved_me` key/value pair.)

**Comment by alexmarchant** [comment]
@jmduke ok, likely a problem with the https://github.com/PlugForMac/HypeMachineAPI Library, will create an issue over there.
