### ISSUE TITLE
Space bar toggles pause/play

### ISSUE THREAD

**Issue by alexmarchant** [PlugForMac/Plug2Issues#95]

**Comment by maxkrieger** [comment]
:+1: really need! Media keys work fine for now, luckily.

**Comment by j0b0sapi3n** [comment]
Looking forward to this one!

**Comment by rodrigopr** [comment]
+1 :+1:

**Comment by perks** [comment]
+1 :+1:

**Comment by alexmarchant** [comment]
@maxkrieger @j0b0sapi3n @rodrigopr @perks P.S. we're not technically open-source, but if any of you are developers, would love to invite you to the repo to contribute here :)

**Comment by maxkrieger** [comment]
@alexmarchant What's your stack look like? Looks a bit too fast to be webkit-based :P

**Comment by alexmarchant** [comment]
@maxkrieger ya we're all swift :bird:

**Comment by rodrigopr** [comment]
@alexmarchant, I don't know much about swift, but I can try to contribute to this and other features. :)

**Comment by alexmarchant** [comment]
@rodrigopr I'll invite you to our slack team (via your github email, let me know if this is wrong), we can chat more there.

**Comment by alexmarchant** [comment]
@teendev just contributed some code that will make this happen. Looking to push a release today with this code. Thanks @teendev!
