### ISSUE TITLE
Make <3 button bigger!

### ISSUE THREAD

**Issue by maxkrieger** [PlugForMac/Plug2Issues#96]
:heart:'ing songs is an integral part of hypem, and making the button nice and big in Plug1 was really nice to have.

**Comment by alexmarchant** [comment]
Hey @maxkrieger I'm going to close this issue for now. If we hear about this from more people I'll open it back up. Thanks you for the feedback!

**Comment by maxkrieger** [comment]
No problem! Thanks for the awesome app.
