### ISSUE TITLE
Preferences option to show album artwork

### ISSUE THREAD

**Issue by stursby** [PlugForMac/Plug2Issues#97]
Is there a to get the album artwork back? (like in the old version of Plug). Maybe I'm the only one on this, but I'm a visual person and would love to see the artwork.

Maybe this could be a setting under preferences?

Here's a quick mockup:

![artwork](https://cloud.githubusercontent.com/assets/527849/11643019/ee10a90e-9d06-11e5-94fa-babc521d5270.png)

**Comment by perks** [comment]
Definitely missing this option as well.

**Comment by jschut** [comment]
+1

**Comment by nlpthk** [comment]
+1

**Comment by vhmth** [comment]
+1

**Comment by vhmth** [comment]
https://twitter.com/vhmth/status/679422204883283968

**Comment by TechnoTom74** [comment]
+1

**Comment by opula** [comment]
+1

**Comment by nichm** [comment]
+1

**Comment by samuelkraft** [comment]
+1
