### ISSUE TITLE
Sidebar - Get Rid of the Hover State

### ISSUE THREAD

**Issue by philipamour** [PlugForMac/Plug2Issues#98]
Please get rid of the hover state on the sidebar icons (Trending, Heart, History, etc.), it makes the app feel like a webapp. There is no hover state on navigational elements (in most of the cases) in OS X Apps.

**Comment by alexmarchant** [comment]
looping in @glennui

**Comment by glennui** [comment]
Yeah, I'd be fine with removing the hover states on the sidebar. Keeps it consistent with other apps people may be using alongside Plug. Thanks @philipamour!
